- hosts: Kubernetes_Master
  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      ansible.builtin.copy:
        src: "/home/slaveadmin/workspace/Health-Care/deployment.yaml"
        dest: "/tmp/deployment.yaml"

    - name: Execute kubectl create command
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        sudo kubectl create -f /tmp/deployment.yaml
      ignore_errors: yes

    - name: Wait for 10 seconds
      pause:
        seconds: 10

    - name: Get list of pods and node IPs
      shell: sudo kubectl get pods -o wide
      register: pod_list
      ignore_errors: yes

    - name: Display pod list and node IPs
      debug:
        var: pod_list.stdout_lines
